version: "3"
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - $HOME/Pay Later Group/micro-services/mobile/storage/logs:/logs/ms/mobile/
      - $HOME/Pay Later Group/micro-services/external-service/storage/logs:/logs/ms/external-service/
      - $HOME/Pay Later Group/micro-services/address/storage/logs:/logs/ms/address/
      - $HOME/Pay Later Group/micro-services/merchant/storage/logs:/logs/ms/merchant/
      - $HOME/Pay Later Group/micro-services/merchant-portal/storage/logs:/logs/ms/merchant-portal/
      - $HOME/Pay Later Group/micro-services/customer-portal/storage/logs:/logs/ms/customer-portal/
      - $HOME/Pay Later Group/micro-services/accounts/storage/logs:/logs/ms/accounts/
      - $HOME/Pay Later Group/micro-services/communications/storage/logs:/logs/ms/communications/
      - $HOME/Pay Later Group/micro-services/documents/storage/logs:/logs/ms/documents/
      - $HOME/Pay Later Group/micro-services/payments/storage/logs:/logs/ms/payments/
      - /var/tmp/unified-log:/logs/legacy/lmp
      - $HOME/Pay Later Group/legacy/CLL/storage/logs:/logs/legacy/cll
      - $HOME/.config/valet/Log:/logs/nginx

    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.2.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
